version: '3'
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD:/var/jenkins_home
    restart: unless-stopped

  tomcat:
    image: tomcat:latest
    ports:
      - "8082:8080"
    volumes:
      - $PWD:/usr/local/tomcat/webapps/status
    restart: unless-stopped

